apiVersion: apps/v1
kind: Deployment
metadata:
  name: electro-ui
  labels:
    app: electro-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electro-ui
  template:
    metadata:
      labels:
        app: electro-ui
    spec:
      containers:
        - name: electro-ui
          image: electro-ui
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9004
          env:
            - name: PORT
              value: "9004"