apiVersion: v1
kind: Service
metadata:
  name: electro-ui
  labels:
    app: electro-ui
spec:
  type: ClusterIP
  selector:
    app: electro-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9004