electro:
  catalog-service-uri: http://catalog-service
spring:
  flyway:
    url: jdbc:postgresql://electro-postgres/electrodb_order
  r2dbc:
    url: r2dbc:postgresql://polar-postgres/electrodb_order
  rabbitmq:
    host: electro-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://electro-keycloak/realms/ElectroMarket