server:
  port: 9006
  shutdown: graceful
  netty:
    connection-timeout: 2s
    keep-alive-timeout: 15s

spring:
  application:
    name: mail-service
  mail:
    host: smtp.zoho.com
    port: 587
    username: ${ZOHO_MAIL_USERNAME:''}
    password: ${ZOHO_MAIL_PASSWORD:''}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: confirmationRequest
    stream:
      bindings:
        confirmationSent-out-0:
          destination: confirmation-sent
        confirmationRequest-in-0:
          destination: confirmation-request
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ElectroMarket
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: ElectroMarket

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
