spring:
  data:
    redis:
      host: electro-redis
      ssl:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://electro-keycloak/realms/ElectroMarket
