apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: electro-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - electromarket.us.to
    secretName: tls-certificate
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edge-service
            port:
              number: 80
