apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: electro-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge-service
                port:
                  number: 80
$schema: https://kubernetesjsonschema.dev/v1.21.0-standalone/networking-v1.json
