apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: electro-ingress
spec:
  ingressClassName: nginx
  validation.k8s.io/schema: /path/to/local/schema/ingress-networking-v1.json
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge-service
