apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: electro-ingress
spec:
  ingressClassName: nginx
# tls:
# - hosts:
#   - electromarket.site
#   secretName: electro-tls-secret
  rules:
    - host: electromarket.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge-service
                port:
                  number: 80
