version: "3.8"
services:
  catalog:
    depends_on:
      - electro-postgres
    image: catalog
    container_name: catalog
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://electro-postgres:5432/electrodb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  electro-postgres:
    image: "postgres:14.4"
    container_name: "electro-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: electrodb_catalog
