apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/tomerazuz/payment-service
          ports:
            - containerPort: 9102
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'