apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../mail-service/k8s

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: mail-config

images:
- name: mail-service
  newName: ghcr.io/tomerazuz/mail-service
  newTag: d622f71177bf48aa6bfda9ea384c692bdb15a11f

replicas:
- count: 1
  name: mail-service
