apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  template:
    spec:
      containers:
        - name: mail-service
          volumeMounts:
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: zoho-credentials-volume
              mountPath: /workspace/secrets/zoho
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: rabbitmq-credentials-volume
          secret:
            secretName: electro-rabbitmq-credentials
        - name: zoho-credentials-volume
          secret:
            secretName: electro-zoho-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret