apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  template:
    spec:
      containers:
        - name: mail-service
          resources:
            requests:
              memory: 256Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "2"