apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../order-service/k8s
patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml
configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config
images:
- name: order-service
  newName: ghcr.io/tomerazuz/order-service
  newTag: f273a3fbffb3620719591e68aebc367fe4cdbaea
replicas:
- count: 1
  name: order-service
