apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../payment-service/k8s

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: payment-config

images:
  - name: payment-service
    newName: ghcr.io/tomerazuz/payment-service
    newTag: latest

replicas:
  - name: payment-service
    count: 1