apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../edge-service/k8s

patchesStrategicMerge:
  - patch-env.yml
  - patch-ingress.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: edge-config

images:
  - name: edge-service
    newName: ghcr.io/tomerazuz/edge-service
    newTag: 180e3a471d654b3c286ca59b526647188f68845b

replicas:
  - count: 2
    name: edge-service