apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../edge-service/k8s

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/tomerazuz/edge-service
  newTag: 5088fab10fa710370bea7756e7ed303d08770d9d

replicas:
- count: 1
  name: edge-service
