apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../payment-service/k8s

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: payment-config

images:
- name: payment-service
  newName: ghcr.io/tomerazuz/payment-service
  newTag: dd1b1910eaea298daa4aed68bb4295dd344a2efd

replicas:
- count: 1
  name: payment-service
