apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          volumeMounts:
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: paypal-credentials-volume
              mountPath: /workspace/secrets/paypal
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: rabbitmq-credentials-volume
          secret:
            secretName: electro-rabbitmq-credentials
        - name: paypal-credentials-volume
          secret:
            secretName: electro-paypal-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret