name: Catalog Service Commit Stage
on:
  push:
    branches:
      - main
    paths:
      - 'catalog-service/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'
          node-version: '16'

      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high

      - name: Build, unit test, and integration tests
        run: |
          cd catalog-service
          chmod +x mvnw
          ./mvnw install
