name: Order Service Acceptance Stage
on: 
  workflow_run:
    workflows: ['Order Service Commit Stage']
    types: [completed]
    branches: main
concurrency: acceptance # ensures that only one workflow runs at a time

env:
  OWNER: tomerazuz
  REGISTRY: ghcr.io
  APP_REPO: order-service
  DEPLOY_REPO: deployment
  VERSION: ${{ github.sha }}

jobs:
  functional:
    name: Functional Acceptance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running functional acceptance tests"
  performance:
    name: Performance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running performance tests"
  security:
    name: Security Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running security tests"
  deliver:
      name: Deliver release candidate to production
      needs: [ functional, performance, security ]
      runs-on: ubuntu-22.04
      steps:
        - name: Deliver application to production
          uses: peter-evans/repository-dispatch@v2
          with:
            client-payload: '{
              "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.APP_REPO }}",
              "app_name": "${{ env.APP_REPO }}",
              "app_version": "${{ env.VERSION }}"
            }'
